name: bump version

on:
    pull_request:
        types: [closed, labeled]

jobs:
    bump-version-after-merge:
        if: ${{ github.event.label.name == 'bump version after merge' && github.event.pull_request.merged == true}}
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Install dependencies
              run: npm ci

            - name: Fetch PR commit messages
              id: commits
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  gh pr view $PR_NUMBER --repo ${{ github.repository }} --json commits \
                      --jq '.commits[].messageHeadline' >> messages.txt

                  echo "Commit messages:"
                  cat messages.txt
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Determine version bump
              id: bump
              run: |
                  bump="patch"
                  while IFS= read -r line; do
                      echo "Checking: $line"
                      if [[ "$line" == feat* ]]; then
                      bump="minor"
                      elif [[ "$line" == *!:* || "$line" == *BREAKING\ CHANGE* ]]; then
                      bump="major"
                      break
                      fi
                  done < messages.txt

                  echo "Version bump: $bump"
                  echo "bump=$bump" >> $GITHUB_OUTPUT

            - name: Bump version and update Changelog
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  npm version ${{steps.bump.outputs.bump}}

            - name: Push updated package.json and changelog
              run: |
                  git push
