name: publish

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Install dependencies and build
              run: npm ci && npx playwright install --with-deps && npm run build

            - name: Run tests
              run: npm test

    check-pr-labels:
        runs-on: ubuntu-latest
        outputs:
            should_publish: ${{ steps.should_publish.outputs.should_publish }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check PR labels
              id: should_publish
              run: |
                  PR_LABELS=$(gh pr list --state merged --search "${{ github.sha }}" --json labels --jq '.[].labels[].name')
                  if echo "$PR_LABELS" | grep -q "publish"; then
                    echo "Should publish"
                    echo "should_publish=true" >> $GITHUB_OUTPUT
                  else
                    echo "No publish label, skipping"
                    echo "should_publish=false" >> $GITHUB_OUTPUT
                  fi
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish:
        needs: [test, check-pr-labels]
        if: needs.check-pr-labels.outputs.should_publish == 'true'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies and build
              run: npm ci && npm run build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
